### ISSUE TITLE
iOS: could not build using version 8.0.0 --> ld: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by afps1** [hansemannn/titanium-firebase-core#66]
Environment: 
```
──────────────────┤ Check Environment ├───────────────────

Node.js
  ✓  node               installed (v16.13.2)
  ✓  npm                installed (v8.1.2)
 
Titanium CLI
  ✓  cli                up-to-date (v6.1.1)
 
Titanium CLI Dependencies
  ✓  async              up-to-date (v3.2.4)
  ✓  colors             up-to-date (v1.4.0)
  ✓  fields             up-to-date (v0.1.24)
  ✓  got                up-to-date (v11.8.6)
  ✓  humanize           up-to-date (v0.0.9)
  ✓  node-appc          up-to-date (v1.1.6)
  ✓  request            up-to-date (v2.88.2)
  ✓  sprintf            up-to-date (v0.1.5)
  ✓  tmp                up-to-date (v0.2.1)
  ✓  winston            up-to-date (v2.4.6)
  ✓  yauzl              up-to-date (v2.10.0)
 
Titanium SDK
  ✓  latest sdk         installed (v9.3.2.GA)
  ✓  selected sdk       up-to-date (v9.3.2.GA)
 
Mac OS X Environment
  ✓  CLI Tools          installed
 
iOS Environment
  ✓  Xcode              installed (13.4.1)
  ✓  iOS SDK            installed (15.5)
  ✓  WWDR cert          installed
  ✓  developer cert     installed (1 found)
  !  distribution cert  not found
  ✓  dev provisioning   installed (19 found)
  ✓  dist provisioning  installed (4 found)
 
Android Environment
  ✓  sdk                installed (/Users/andresonnenburg/Library/android-sdk-macosx)
  ✓  tools              installed (v26.1.1)
  !  platform tools     untested version 34.0.1; may or may not work
  ✓  build tools        installed (v31.0.0)
  ✓  adb                installed /Users/andresonnenburg/Library/android-sdk-macosx/platform-tools/adb
  ✓  emulator           installed /Users/andresonnenburg/Library/android-sdk-macosx/tools/emulator
  ✓  targets            installed (8 found)
  ✓  avds               installed (1 found)
  !  ndk                Android NDK not found
 
Java Development Kit
  ✓  jdk                installed (v11.0.17)
  ✓  java               installed /Library/Java/JavaVirtualMachines/jdk-11.0.17.jdk/Contents/Home/bin/java
  ✓  javac              installed /Library/Java/JavaVirtualMachines/jdk-11.0.17.jdk/Contents/Home/bin/javac
  ✓  keytool            installed /Library/Java/JavaVirtualMachines/jdk-11.0.17.jdk/Contents/Home/bin/keytool
  ✓  jarsigner          installed /Library/Java/JavaVirtualMachines/jdk-11.0.17.jdk/Contents/Home/bin/jarsigner
 
Intel® Hardware Accelerated Execution Manager (HAXM)
  ✓  compatible         
  !  installed          not found; install HAXM to use Android x86 emulator
 
Network
  ✓  online             
  -  no proxy server configured 
  ✓  Network connection test 
  ✓  Java-based connection test 
 
Directory Permissions
  ✓  home directory     
  ✓  titanium config directory 
  ✓  titanium sdk install directory 
  ✓  workspace directory 
  ✓  temp directory  
```

`ti build --platform ios --device-id mydeviceid  --deploy-type development --force-copy --device-family iphone --target device`

I got this error with version 8.0.0 ( both core & cloudmessaging) . With previous version (7.2.0) it goes ok.
```
[TRACE] ld: symbol(s) not found for architecture arm64
[TRACE] clang: error: linker command failed with exit code 1 (use -v to see invocation)

[ERROR] 2023-03-24 20:37:57.990 xcodebuild[33858:723410] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
[ERROR] 2023-03-24 20:37:57.991 xcodebuild[33858:723410] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
etc...
etc...
```

**Comment by m1ga** [comment]
You are using Ti 9.3.1. That is very outdated! 
The latest module version has minSdk set to 10.0.0 https://github.com/hansemannn/titanium-firebase-core/blob/main/ios/manifest#L19
so you'll need to update in order to use it

**Comment by afps1** [comment]
Hi, In fact I am using 12.0.0.GA. For some reason the "check environment" gave the minimum SDK version installed. To guarantee, I had removed all old versions. This is what I 've got: 
```

[TRACE] ld: warning: directory not found for option '-L/Users/andresonnenburg/Desktop/Glomer/build/iphone/lib'
[TRACE] ld: warning: Could not find or use auto-linked framework 'FBLPromises'
[TRACE] Undefined symbols for architecture arm64:
[TRACE]   "_objc_msgSend$numberWithInt:", referenced from:
[TRACE]       -[FirebaseCoreModule LOG_LEVEL_ERROR] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE]       -[FirebaseCoreModule LOG_LEVEL_WARNING] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE]       -[FirebaseCoreModule LOG_LEVEL_NOTICE] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE]       -[FirebaseCoreModule LOG_LEVEL_INFO] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE]       -[FirebaseCoreModule LOG_LEVEL_DEBUG] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE]   "_objc_msgSend$debugEnabled", referenced from:
[TRACE]       -[FirebaseCoreModule configure:] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE]   "_objc_msgSend$defaultConfig", referenced from:
[TRACE]       -[FirebaseCoreModule configure:] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE]   "_objc_msgSend$mainBundle", referenced from:
[TRACE]       -[FirebaseCoreModule configure:] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE]   "_objc_msgSend$appDidReceiveMessage:", referenced from:
[TRACE]       -[FirebaseCloudmessagingModule appDidReceiveMessage:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]   "_objc_msgSend$isEqualToString:", referenced from:
[TRACE]       -[FirebaseCoreModule configure:] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE]   "_objc_msgSend$stringByDeletingPathExtension", referenced from:
[TRACE]       -[FirebaseCoreModule configure:] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE]   "_objc_msgSend$pathExtension", referenced from:
[TRACE]       -[FirebaseCoreModule configure:] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE]   "_objc_msgSend$dataUsingEncoding:", referenced from:
[TRACE]       -[FirebaseCloudmessagingModule setApnsToken:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]   "_objc_msgSend$configureWithName:options:", referenced from:
[TRACE]       -[FirebaseCoreModule configure:] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE]   "_objc_msgSend$initWithGoogleAppID:GCMSenderID:", referenced from:
[TRACE]       -[FirebaseCoreModule configure:] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE]   "_objc_msgSend$configureWithOptions:", referenced from:
[TRACE]       -[FirebaseCoreModule configure:] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE]   "_objc_msgSend$configure", referenced from:
[TRACE]       -[FirebaseCoreModule configure:] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE]   "_objc_msgSend$_hasListeners:", referenced from:
[TRACE]       -[FirebaseCloudmessagingModule messaging:didReceiveRegistrationToken:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]   "_objc_msgSend$dictionaryWithObjects:forKeys:count:", referenced from:
[TRACE]       ___43-[FirebaseCloudmessagingModule fetchToken:]_block_invoke in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       ___44-[FirebaseCloudmessagingModule deleteToken:]_block_invoke in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       ___55-[FirebaseCloudmessagingModule deleteTokenForSenderID:]_block_invoke in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule messaging:didReceiveRegistrationToken:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]   "_objc_msgSend$count", referenced from:
[TRACE]       -[FirebaseCloudmessagingModule subscribeToTopic:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule unsubscribeFromTopic:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule fetchToken:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule deleteToken:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule deleteTokenForSenderID:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule appDidReceiveMessage:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCoreModule configure:] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE]       ...
[TRACE]   "_objc_msgSend$messaging", referenced from:
[TRACE]       -[FirebaseCloudmessagingModule _initWithPageContext:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule fcmToken] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule setApnsToken:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule subscribeToTopic:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule unsubscribeFromTopic:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule fetchToken:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule deleteToken:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       ...
[TRACE]   "_objc_msgSend$arrayWithObjects:count:", referenced from:
[TRACE]       ___43-[FirebaseCloudmessagingModule fetchToken:]_block_invoke in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       ___44-[FirebaseCloudmessagingModule deleteToken:]_block_invoke in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       ___55-[FirebaseCloudmessagingModule deleteTokenForSenderID:]_block_invoke in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]   "_objc_msgSend$setDelegate:", referenced from:
[TRACE]       -[FirebaseCloudmessagingModule _initWithPageContext:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]   "_objc_msgSend$defaultOptions", referenced from:
[TRACE]       -[FirebaseCoreModule configure:] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE]   "_objc_msgSend$call:thisObject:", referenced from:
[TRACE]       ___43-[FirebaseCloudmessagingModule fetchToken:]_block_invoke in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       ___44-[FirebaseCloudmessagingModule deleteToken:]_block_invoke in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       ___55-[FirebaseCloudmessagingModule deleteTokenForSenderID:]_block_invoke in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]   "_objc_msgSend$numberWithBool:", referenced from:
[TRACE]       ___44-[FirebaseCloudmessagingModule deleteToken:]_block_invoke in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       ___55-[FirebaseCloudmessagingModule deleteTokenForSenderID:]_block_invoke in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCoreModule configure:] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE]   "_objc_msgSend$pathForResource:ofType:", referenced from:
[TRACE]       -[FirebaseCoreModule configure:] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE]   "_objc_msgSend$tokenWithCompletion:", referenced from:
[TRACE]       -[FirebaseCloudmessagingModule fetchToken:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]   "_objc_msgSend$intValue:", referenced from:
[TRACE]       -[FirebaseCoreModule setLogLevel:] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE]   "_objc_msgSend$objectAtIndex:", referenced from:
[TRACE]       -[FirebaseCloudmessagingModule subscribeToTopic:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule unsubscribeFromTopic:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule fetchToken:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule deleteToken:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule deleteTokenForSenderID:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule appDidReceiveMessage:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCoreModule configure:] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE]       ...
[TRACE]   "_objc_msgSend$stringWithFormat:", referenced from:
[TRACE]       -[FirebaseCloudmessagingModule subscribeToTopic:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule unsubscribeFromTopic:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule fetchToken:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule deleteToken:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule deleteTokenForSenderID:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule appDidReceiveMessage:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]   "_objc_msgSend$throwException:subreason:location:", referenced from:
[TRACE]       -[FirebaseCloudmessagingModule subscribeToTopic:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule unsubscribeFromTopic:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule fetchToken:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule deleteToken:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule deleteTokenForSenderID:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule appDidReceiveMessage:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]   "_objc_msgSend$FCMToken", referenced from:
[TRACE]       -[FirebaseCloudmessagingModule fcmToken] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]   "_objc_msgSend$registerApplicationDelegate:", referenced from:
[TRACE]       -[FirebaseCloudmessagingModule _configure] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]   "_objc_msgSend$null", referenced from:
[TRACE]       -[FirebaseCloudmessagingModule fcmToken] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule fetchToken:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       ___43-[FirebaseCloudmessagingModule fetchToken:]_block_invoke in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule deleteToken:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule messaging:didReceiveRegistrationToken:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]   "_objc_msgSend$sharedInstance", referenced from:
[TRACE]       -[FirebaseCoreModule setLogLevel:] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE]   "_objc_msgSend$deleteTokenWithCompletion:", referenced from:
[TRACE]       -[FirebaseCloudmessagingModule deleteToken:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]   "_objc_msgSend$setAPNSToken:", referenced from:
[TRACE]       -[FirebaseCloudmessagingModule setApnsToken:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule application:didRegisterForRemoteNotificationsWithDeviceToken:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]   "_objc_msgSend$subscribeToTopic:", referenced from:
[TRACE]       -[FirebaseCloudmessagingModule subscribeToTopic:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]   "_objc_msgSend$defaultApp", referenced from:
[TRACE]       -[FirebaseCoreModule configure:] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE]   "_objc_msgSend$setValue:forKey:", referenced from:
[TRACE]       -[FirebaseCoreModule configure:] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE]   "_objc_msgSend$app", referenced from:
[TRACE]       -[FirebaseCloudmessagingModule _configure] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]   "_objc_msgSend$deleteFCMTokenForSenderID:completion:", referenced from:
[TRACE]       -[FirebaseCloudmessagingModule deleteTokenForSenderID:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]   "_objc_msgSend$class", referenced from:
[TRACE]       -[FirebaseCloudmessagingModule subscribeToTopic:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule unsubscribeFromTopic:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule fetchToken:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule deleteToken:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule deleteTokenForSenderID:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule appDidReceiveMessage:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]   "_objc_msgSend$setLoggerLevel:", referenced from:
[TRACE]       -[FirebaseCoreModule setLogLevel:] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE]   "_objc_msgSend$localizedDescription", referenced from:
[TRACE]       ___43-[FirebaseCloudmessagingModule fetchToken:]_block_invoke in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       ___44-[FirebaseCloudmessagingModule deleteToken:]_block_invoke in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       ___55-[FirebaseCloudmessagingModule deleteTokenForSenderID:]_block_invoke in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]   "_objc_msgSend$reason", referenced from:
[TRACE]       -[FirebaseCoreModule configure:] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE]   "_objc_msgSend$unsubscribeFromTopic:", referenced from:
[TRACE]       -[FirebaseCloudmessagingModule unsubscribeFromTopic:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]   "_objc_msgSend$isKindOfClass:", referenced from:
[TRACE]       -[FirebaseCloudmessagingModule subscribeToTopic:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule unsubscribeFromTopic:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule fetchToken:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule deleteToken:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule deleteTokenForSenderID:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]       -[FirebaseCloudmessagingModule appDidReceiveMessage:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]   "_objc_msgSend$objectForKey:", referenced from:
[TRACE]       -[FirebaseCoreModule configure:] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE]   "_objc_msgSend$fireEvent:withObject:", referenced from:
[TRACE]       -[FirebaseCloudmessagingModule messaging:didReceiveRegistrationToken:] in libfirebase.cloudmessaging.a(FirebaseCloudmessagingModule.o)
[TRACE]   "_objc_msgSend$initWithContentsOfFile:", referenced from:
[TRACE]       -[FirebaseCoreModule configure:] in libfirebase.core.a(FirebaseCoreModule.o)
[TRACE] ld: symbol(s) not found for architecture arm64
[TRACE] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] 2023-03-25 21:39:35.645 xcodebuild[39821:876099] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
[ERROR] 2023-03-25 21:39:35.645 xcodebuild[39821:876099] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
[ERROR] ** BUILD FAILED **
[ERROR] The following build commands failed:
[ERROR]         Ld /Users/andresonnenburg/Desktop/Glomer/build/iphone/build/Products/Debug-iphoneos/Glomer.app/Glomer normal (in target 'Glomer' from project 'Glomer')
[ERROR] (1 failure)

```

Environment


```

Titanium CLI
  ✓  cli                up-to-date (v6.1.1)
 
Titanium CLI Dependencies
  ✓  async              up-to-date (v3.2.4)
  ✓  colors             up-to-date (v1.4.0)
  ✓  fields             up-to-date (v0.1.24)
  ✓  got                up-to-date (v11.8.6)
  ✓  humanize           up-to-date (v0.0.9)
  ✓  node-appc          up-to-date (v1.1.6)
  ✓  request            up-to-date (v2.88.2)
  ✓  sprintf            up-to-date (v0.1.5)
  ✓  tmp                up-to-date (v0.2.1)
  ✓  winston            up-to-date (v2.4.6)
  ✓  yauzl              up-to-date (v2.10.0)
 
Titanium SDK
  ✓  latest sdk         installed (v12.0.0.GA)
  ✓  selected sdk       up-to-date (v12.0.0.GA)
 
Mac OS X Environment
  ✓  CLI Tools          installed
 
iOS Environment
  ✓  Xcode              installed (13.4.1)
  ✓  iOS SDK            installed (15.5)
  ✓  WWDR cert          installed
  ✓  developer cert     installed (1 found)
  !  distribution cert  not found
  ✓  dev provisioning   installed (19 found)
  ✓  dist provisioning  installed (4 found)

```

**Comment by m1ga** [comment]
I never used `--force-copy` to build an app. Did you try it without? I use 8.0.0 for many month and never had that issue or saw it in the issues or slack before. Can't help you more because I'm not familiar with that iOS error.

Side node:
and as you can see in my edit of your first post: please use code blocks to format it. Makes it much easier to read what your text is and what a code/output block is

**Comment by afps1** [comment]
I removed the --force-copy from the build. Same error.  BTW, thank you very much for the prompt help !


```
[TRACE] ld: symbol(s) not found for architecture arm64
[TRACE] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] 2023-03-26 10:44:24.309 xcodebuild[47685:1134368] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
[ERROR] 2023-03-26 10:44:24.309 xcodebuild[47685:1134368] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
[ERROR] ** BUILD FAILED **
[ERROR] The following build commands failed:
[ERROR]         Ld /Users/andresonnenburg/Desktop/Glomer/build/iphone/build/Products/Debug-iphoneos/Glomer.app/Glomer normal (in target 'Glomer' from project 'Glomer')
[ERROR] (1 failure)
```

**Comment by m1ga** [comment]
https://user-images.githubusercontent.com/4334997/227781262-ed5c7363-bd4e-4879-ba58-da19bb0853c9.mp4

simulator opened after a bit, then I've added the `require("firebase.core")` into the app.js and build it to my device. Still works.

`tq` is my short-cut for the `ti build...` command, so nothing special.

**Comment by afps1** [comment]
I found this post: 

[](https://stackoverflow.com/questions/71320584/flutter-build-ios-got-error-requested-but-did-not-find-extension-point-with-ide)

Seems to be an issue with XCODE 13.3 & 13.4... I will try to downgrade it to 13.2 and put the results here.

**Comment by afps1** [comment]
I found the post bellow. Seems to be an issue with xcode 13.3 / 13.4. Will try to downgrade to 13.2 and put the results here. 

[](https://stackoverflow.com/questions/71320584/flutter-build-ios-got-error-requested-but-did-not-find-extension-point-with-ide)

**Comment by m1ga** [comment]
since you've just mentioned the xcode version: you should use 14.x. I think that is the current min sdk for stores anyways

**Comment by afps1** [comment]
Will try both ( 13.2 and 14.) and put the results here...But there is a confirmed bug with xcode 13.3 and 13.4 

https://stackoverflow.com/questions/71320584/flutter-build-ios-got-error-requested-but-did-not-find-extension-point-with-ide

https://stackoverflow.com/questions/71542933/flutter-for-ios-run-build-but-not-archive/71545619#71545619

**Comment by afps1** [comment]
Worked on XCODE version 14.2 :)
